---
- name: Stop systemctl firewalld
  command: systemctl stop firewalld.service
  when: ansible_distribution_major_version|int >= 7

- name: Disable systemctl firewalld
  command: systemctl disable firewalld.service
  when: ansible_distribution_major_version|int >= 7

- name: Install iptables
  yum: name=iptables state=installed

- name: Install iptables related packages
  yum: name=iptables-services state=installed
  when: ansible_distribution_major_version|int >= 7

- name: Flush iptables
  yum: name=iptables-services state=installed
  when: iptables_remove_rules

- name: Create the iptables for IPv4
  template: >
      src=iptables4.j2
      dest=/etc/sysconfig/iptables
      owner=root
      group=root
      mode=0600
      backup=yes
  notify: restart iptables

- name: Enable and start iptables
  service: name=iptables state=started enabled=yes

# - name: Create the iptables for IPv6
#   template: >
#       src=iptables6.j2
#       dest=/etc/sysconfig/ip6tables
#       owner=root
#       group=root
#       mode=0600
#       backup=yes
#   notify: restart ip6tables
#   when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"
#
# - name: enable and start ip6tables service
#   service: name=ip6tables state=started enabled=yes
#   when: "'scope' in ansible_default_ipv6 and ansible_default_ipv6.scope == 'global'"
