---
- name: Stop systemctl firewalld and disable
  service: name=firewalld.service state=stopped enabled=no
  when: ansible_distribution_major_version|int >= 7

- name: Install iptables
  yum: name='{{iptables_service_name}}' state=installed

- name: Install iptables related packages
  yum: name=iptables-services state=installed
  when: ansible_distribution_major_version|int >= 7
