---
# handlers file for ansible-iptables
- name: restart iptables
  service: name='{{iptables_service_name}}' state=restarted

- name: restart iptables6
  service: name='{{iptables6_service_name}}' state=restarted
